[package]
name = "ihtc2024chen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
itertools = "0.13.0"
minilp = "0.2.2"
rand = "0.8.5"